name: Build MTabs WebView
on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    container:
      image: androidcontainer/android-sdk-ndk:api-29-r10e-slim
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            default-jdk \
            autoconf \
            libtool
          python -m pip install --upgrade pip
          pip install Cython==0.29.33
          pip install buildozer==1.5.0
          pip install kivy

      - name: Ensure SDK licenses
        run: |
          mkdir -p /opt/android/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > /opt/android/licenses/android-sdk-license

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer android debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MTabs WebView APK
          path: bin/*.apk
