name: Build MTabs WebView
on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev
          python -m pip install --upgrade pip
          pip install "Cython<3.0.0"
          pip install buildozer==1.5.0
          pip install kivy==2.2.1
          pip install kivymd==1.1.1

      - name: Setup Android SDK & NDK
        uses: android-actions/setup-android@v3
        
      - name: Install Android SDK components
        run: |
          echo "y" | sdkmanager "platforms;android-33" "build-tools;33.0.2"
          echo "y" | sdkmanager "ndk;25.2.9519653"
          
      - name: Set NDK path
        run: |
          echo "ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer android debug
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/25.2.9519653
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/25.2.9519653

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MTabs WebView APK
          path: bin/*.apk
