name: Build MTabs WebView
on: [push, pull_request]
 
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
 
      - name: Cache Buildozer dependencies
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
 
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: '1.4.0'  # Menentukan versi spesifik
          command: buildozer android debug
 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MTabs WebView APK
          path: ${{ steps.buildozer.outputs.filename }}
