name: Build MTabs WebView
on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libjaxb-java
            
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.33
          pip install buildozer==1.5.0
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        env:
          SKIP_JDK_VERSION_CHECK: true

      - name: Install Android SDK components
        run: |
          echo "y" | sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-33" "build-tools;33.0.2"
          echo "y" | sdkmanager --sdk_root=$ANDROID_HOME "ndk;25.2.9519653"
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          ANDROID_HOME: /usr/local/lib/android/sdk
          CLASSPATH: /usr/share/java/jaxb-api.jar:/usr/share/java/jaxb-impl.jar
          SKIP_JDK_VERSION_CHECK: true

      - name: Build APK
        run: |
          buildozer android debug
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/25.2.9519653
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MTabs WebView APK
          path: bin/*.apk
