name: Build MTabs WebView
on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev
          python -m pip install --upgrade pip
          pip install "Cython<3.0.0"  # Gunakan versi Cython yang stabil
          pip install buildozer==1.5.0  # Pin ke versi spesifik
          pip install kivy

      - name: Setup buildozer
        run: |
          cd $GITHUB_WORKSPACE
          buildozer init  # Buat buildozer.spec jika belum ada
          # Tunggu sebentar untuk memastikan file tercipta
          sleep 2
          cat buildozer.spec  # Tampilkan isi file untuk debugging

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer android debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MTabs WebView APK
          path: bin/*.apk
