name: Build MTabs WebView
on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build APK
        run: |
          buildozer init || true
          buildozer android debug
        env:
          BUILDOZER_NO_INTERNET: 1
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MTabs WebView APK
          path: bin/*.apk
